extends Node

enum PlayerType {NONE, TAGGER, HIDER}
enum PlayerStatus {NONE, FROZEN, UNFROZEN}
enum GameStatus {LOBBY, IN_GAME}
enum HiderColor {RED, GREEN, BLUE}

# MAKE SURE TO PUT WHAT EVER THE ACTUAL LAYER NUMBER IS MINUS 1 WHEN DOING SHIFT OPERATOR
const LAYER_INTERACT = 1 << 4
const LAYER_FREEZE = 1 << 31
const LAYER_UNFREEZE = 1 << 30
